export const coursesData = [
    {
        id: 0,
        title: ['Python', 'Python'],
        description: ['Всеобъемлющее введение в один из самых популярных языков программирования в мире. Мы поможем вам освоить основы языка, научиться работать с данными, создавать веб-приложения и автоматизировать задачи с помощью Python. Этот курс отлично подойдет как для начинающих, так и для опытных программистов.', "A comprehensive introduction to one of the most popular programming languages in the world. We'll help you learn the basics of the language, learn how to work with data, build web applications, and automate tasks with Python. This course is perfect for both beginners and experienced programmers."],
        logo: 'python',
        discount: 0,
        queryField: 'питон, пайтон python',
        popularity: 10,
        date: 1621216800,
        entity: 'programming language',
    },
    {
        id: 1,
        title: ['C++', 'C++'],
        description: ['Освойте программирование на одном из мощнейших языков в мире. Изучите его основы, а также более продвинутые темы: ООП, работа с памятью, многопоточность... Наш курс позволит вам создавать высокопроизводительные приложения и игры, а также работать над проектами в области робототехники и автоматизации.', 'Learn to code in one of the most powerful languages in the world. Learn its basics, as well as more advanced topics: OOP, memory management, multithreading... Our course will allow you to create high-performance applications and games, as well as work on projects in the field of robotics and automation.'],
        logo: 'cpp',
        discount: 20,
        queryField: 'c++ С++ с',
        popularity: 8,
        date: 1621130400,
        entity: 'programming language',
    },
    {
        id: 2,
        title: ['JavaScript', 'JavaScript'],
        description: ['Хотите ли вы создавать крутые интерактивные веб-сайты? Тогда, получите практические навыки по работе с JavaScript. Наша программа включает в себя изучение современных технологий, таких как React и Node.js, которые позволят вам создавать более сложные и масштабируемые проекты.', 'Do you want to create cool interactive websites? Then, get practical skills in working with JavaScript. Our program includes the study of modern technologies such as React and Node.js, which will allow you to create more complex and scalable projects.'],
        logo: 'js',
        discount: 10,
        queryField: 'джава джаваскрипт жава жаваскрипт JavaScript',
        popularity: 9.9,
        date: 1621044000,
        entity: 'programming language',
    },
    {
        id: 3,
        title: ['Full Stack Разработчик', 'Full Stack Development'],
        description: ['Обширный курс, охватывающий как фронтенд, так и бэкенд разработку. Вы научитесь создавать современные веб-приложения, освоите основы фронтенд разработки на HTML, CSS и JavaScript, бэкенд разработки на PHP, Node.js и базы данных MySQL и PostgreSQL. Этот курс идеально подойдет для тех, кто хочет стать полноценным разработчиком приложений.', 'An extensive course covering both front-end and back-end development. You will learn how to create modern web applications, master the basics of front-end development in HTML, CSS and JavaScript, back-end development in PHP, Node.js and MySQL and PostgreSQL databases. This course is ideal for those who want to become a full-fledged application developer.'],
        logo: 'fullstack',
        discount: 0,
        queryField: 'полный стек полный стэк разработчик Full Stack',
        popularity: 9,
        date: 1621044000,
        entity: 'profession',
    },
    {
        id: 4,
        title: ['PHP', 'PHP'],
        description: ['Всеобъемлющее введение в разработку с использованием языка программирования PHP. Вы научитесь создавать динамические веб-приложения, работать с базами данных и разрабатывать эффективные серверные решения. Этот курс позволит вам освоить основы PHP и стать уверенным разработчиком на этой платформе.', 'A comprehensive introduction to development using the PHP programming language. You will learn how to build dynamic web applications, work with databases, and develop efficient server-side solutions. This course will allow you to master the basics of PHP and become a confident PHP developer.'],
        logo: 'php',
        discount: 0,
        queryField: 'пхп пиэчпи backend PHP',
        popularity: 10,
        date: 1620957600,
        entity: 'programming language',
    },
    {
        id: 5,
        title: ['Backend Разработчик', 'Backend Development'],
        description: ['Интенсивный курс, посвященный разработке бэкенд-части веб-приложений. Вы научитесь создавать и оптимизировать серверную логику, работать с базами данных и обеспечивать безопасность данных. В рамках курса будут рассмотрены языки программирования PHP, Node.js и базы данных MySQL и PostgreSQL, а также основы веб-серверов и API.', 'An intensive course dedicated to the development of the back-end part of web applications. You will learn how to create and optimize server logic, work with databases and ensure data security. The course will cover the programming languages PHP, Node.js and MySQL and PostgreSQL databases, as well as the basics of web servers and APIs.'],
        logo: 'backend',
        discount: 0,
        queryField: 'разработчик Backend Development',
        popularity: 8,
        date: 1620871200,
        entity: 'profession',
    },
    {
        id: 6,
        title: ['Технический Английский', 'Technical English'],
        description: ['Курс, направленный на развитие навыков использования английского языка в сфере информационных технологий. Вы узнаете специфическую терминологию, научитесь читать и понимать техническую документацию, а также сможете эффективно коммуницировать с коллегами на английском языке. Курс также включает практическиезадания и обучающие материалы для самостоятельного изучения.', 'A course aimed at developing the skills of using English in the field of information technology. You will learn specific terminology, learn to read and understand technical documentation, and communicate effectively with colleagues in English. The course also includes practical tasks and teaching materials for self-study.'],
        logo: 'english',
        discount: 0,
        queryField: ' Технический английский язык Technical English',
        popularity: 7,
        date: 1620784800,
        entity: 'language',
    },
    {
        id: 7,
        title: ['Алгоритмы и Структуры данных', 'Algorithms and Data Structures'],
        description: ['Курс, который поможет вам понять и применять различные алгоритмы и структуры данных в своих проектах. Вы изучите основные алгоритмические подходы и поймете, как выбрать наиболее эффективные решения для решения задач. Курс также включает практические задания и примеры реализации алгоритмов на популярных языках программирования.', 'A course that will help you understand and apply various algorithms and data structures in your projects. You will learn the basic algorithmic approaches and understand how to choose the most efficient solutions for solving problems. The course also includes practical tasks and examples of the implementation of algorithms in popular programming languages.'],
        logo: 'algorithms',
        discount: 0,
        queryField: 'алгоритмы данные данных структура структуры теория Algorithms and Data Structures',
        popularity: 9,
        date: 1620698400,
        entity: 'programming',
    },
    {
        id: 8,
        title: ['Bulma', 'Bulma'],
        description: ['Курс, посвященный изучению фреймворка Bulma - мощного инструмента для разработки современных и отзывчивых веб-интерфейсов. Вы научитесь использовать основные компоненты Bulma, создавать адаптивные макеты и применять стилизацию для достижения профессионального вида вашего веб-приложения.',"A course dedicated to learning the Bulma framework, a powerful tool for developing modern and responsive web interfaces. You'll learn how to use Bulma's core components, create responsive layouts, and apply styling to achieve a professional look for your web application."],
        logo: 'bulma',
        discount: 0,
        queryField: 'бульма булма фронт фронтенд frontend Bulma',
        popularity: 6,
        date: 1620612000,
        entity: 'framework',
    },
    {
        id: 9,
        title: ['Bootstrap', 'Bootstrap'],
        description: ['Обширный курс, охватывающий возможности фреймворка Bootstrap для разработки современных и отзывчивых веб-интерфейсов. Вы научитесь создавать адаптивные макеты, использовать готовые компоненты и настраивать стилизацию для достижения профессионального вида вашего веб-приложения.','An extensive course covering the power of the Bootstrap framework for developing modern and responsive web interfaces. You will learn how to create responsive layouts, use ready-made components, and customize styling to achieve a professional look for your web application.'],
        logo: 'bootstrap',
        discount: 0,
        queryField: 'бутстрап frontend фронтенд Bootstrap',
        popularity: 8,
        date: 1620525600,
        entity: 'framework',
    },
    {
        id: 10,
        title: ['Webpack', 'Webpack'],
        description: ['Курс, научающий использовать Webpack - мощный инструмент сборки для разработки веб-приложений. Вы узнаете, как настроить и использовать Webpack для объединения и оптимизации ваших ресурсов, таких как JavaScript, CSS, изображения и многое другое. Курс также включает практические задания для закрепления полученных знаний.',"A course that teaches you how to use Webpack - a powerful build tool for developing web applications. You'll learn how to set up and use Webpack to bundle and optimize your assets like JavaScript, CSS, images, and more. The course also includes practical tasks to consolidate the acquired knowledge."],
        logo: 'webpack',
        discount: 0,
        queryField: 'вебпак фронтенд frontend Webpack',
        popularity: 7,
        date: 1620439200,
        entity: 'tool',
    },
    {
        id: 11,
        title: ['Frontend Разработчик', 'Frontend Development'],
        description: ['Курс, фокусирующийся на разработке пользовательского интерфейса и веб-страниц. Вы научитесь создавать современные и отзывчивые веб-интерфейсы, использовать HTML, CSS и JavaScript для создания интерактивных элементов и оптимизировать производительность вашего фронтенда. Курс также включает основы работы с фреймворками и инструментами разработки.','A course focusing on user interface and web page development. You will learn how to create modern and responsive web interfaces, use HTML, CSS, and JavaScript to create interactive elements, and optimize the performance of your front-end. The course also includes the basics of working with frameworks and development tools.'],
        logo: 'frontend',
        discount: 0,
        queryField: 'фронтенд frontend Разработчик Development',
        popularity: 9,
        date: 1620352800,
        entity: 'profession',
    },
    {
        id: 12,
        title: ['Node.js', 'Node.js'],
        description: ['Интенсивный курс, посвященный разработке серверных приложений на платформе Node.js. Вы научитесь создавать масштабируемые и эффективные серверные решения с использованием JavaScript, работать с базами данных и веб-сокетами, а также освоите принципы построения RESTful API. Курс также включает практические задания и примеры проектов.', 'An intensive course dedicated to the development of server applications on the Node.js platform. You will learn how to build scalable and efficient server-side solutions using JavaScript, work with databases and web sockets, and learn how to build a RESTful API. The course also includes practical assignments and sample projects.'],
        logo: 'node_js',
        discount: 0,
        queryField: 'ноужс ноуджс бэкенд backend Node.js Nodejs',
        popularity: 8,
        date: 1620266400,
        entity: 'platform',
    },
    {
        id: 13,
        title: ['MySQL','MySQL'],
        description: ['Курс, нацеленный на изучение базы данных MySQL - одной из самых популярных систем управления базами данных. Вы научитесь создавать таблицы, выполнять запросы на выборку и модификацию данных, оптимизировать запросы и обеспечивать безопасность вашей базы данных. Курс также включает практические задания и примеры использования MySQL в реальных проектах.','A course aimed at learning the MySQL database - one of the most popular database management systems. You will learn how to create tables, execute queries to select and modify data, optimize queries, and secure your database. The course also includes practical tasks and examples of using MySQL in real projects.'],
        logo: 'mysql',
        discount: 0,
        queryField: 'майскул база базы данных MySQL',
        popularity: 9,
        date: 1620180000,
        entity: 'database',
    },
    {
        id: 14,
        title: ['PostgreSQL','PostgreSQL'],
        description: ['Обширный курс, охватывающий возможности базы данных PostgreSQL - мощной и масштабируемой системы управления базами данных. Вы научитесь создавать таблицы, оптимизировать запросы, использовать транзакции и функции, а также обеспечивать безопасность вашей базы данных. Курс также включает практические задания и примеры использования PostgreSQL в реальных проектах.','An extensive course covering the capabilities of the PostgreSQL database, a powerful and scalable database management system. You will learn how to create tables, optimize queries, use transactions and functions, and secure your database. The course also includes practical tasks and examples of using PostgreSQL in real projects.'],
        logo: 'postgresql',
        discount: 0,
        queryField: 'постгресс пострег база базы данных PostgreSQL',
        popularity: 8,
        date: 1620093600,
        entity: 'database',
    },
    {
        id: 15,
        title: ['MongoDB','MongoDB'],
        description: ['Курс, посвященный изучению базы данных MongoDB - гибкой и масштабируемой NoSQL системы управления данными. Вы научитесь создавать коллекции, выполнять запросы на выборку и модификацию данных, использовать агрегационные функции и обеспечивать безопасность вашей базы данных. Курс также включает практические задания и примеры использования MongoDB в реальных проектах.','A course dedicated to the study of the MongoDB database - a flexible and scalable NoSQL data management system. You will learn how to create collections, execute queries to select and modify data, use aggregation functions, and secure your database. The course also includes practical tasks and examples of using MongoDB in real projects.'],
        logo: 'mongo',
        discount: 0,
        queryField: 'монгодб база базы данных MongoDB',
        popularity: 7,
        date: 1620007200,
        entity: 'database',
    },
    {
        id: 16,
        title: ['Microsoft Word','Microsoft Word'],
        description: ['Курс, нацеленный на освоение основных функций и возможностей текстового редактора Microsoft Word. Вы научитесь создавать и форматировать документы, работать с таблицами и изображениями, использовать шаблоны и стили для создания профессиональных документов. Курс также включает практические задания и советы по повышению производительности работы с Microsoft Word.', 'A course aimed at mastering the basic functions and capabilities of the Microsoft Word text editor. You will learn how to create and format documents, work with tables and images, use templates and styles to create professional documents. The course also includes practical exercises and tips for improving your productivity with Microsoft Word.'],
        logo: 'word',
        discount: 0,
        queryField: 'офис майкрософт ворд Microsoft Word',
        popularity: 8,
        date: 1619920800,
        entity: 'software',
    },
    {
        id: 17,
        title: ['Microsoft Excel', 'Microsoft Excel'],
        description: ['Курс, посвященный изучению основных функций и возможностей электронной таблицы Microsoft Excel. Вы научитесь создавать и форматировать таблицы, выполнять расчеты и анализировать данные, использовать формулы и функции для автоматизации процессов. Курс также включает практические задания и советы по эффективному использованию Microsoft Excel.', 'A course dedicated to learning the basic functions and capabilities of a Microsoft Excel spreadsheet. You will learn how to create and format tables, perform calculations and analyze data, use formulas and functions to automate processes. The course also includes practical exercises and tips for using Microsoft Excel effectively.'],
        logo: 'excel',
        discount: 0,
        queryField: 'офис майкрософт эксель ексель Microsoft Excel',
        popularity: 9,
        date: 1619834400,
        entity: 'software',
    },
    {
        id: 18,
        title: ['Linux', 'Linux'],
        description: ['Интенсивный курс, посвященный операционной системе Linux. Вы научитесь работать с командной строкой, управлять файловой системой, настраивать сеть и безопасность, а также освоите основы автоматизации и скриптования. Курс также включает практические задания и примеры использования Linux в реальных сценариях.', 'An intensive course on the Linux operating system. You will learn how to work with the command line, manage the file system, configure networking and security, as well as master the basics of automation and scripting. The course also includes practical tasks and examples of using Linux in real life scenarios.'],
        logo: 'linux',
        discount: 0,
        queryField: 'линукс ос oc пингвин Linux',
        popularity: 10,
        date: 1619748000,
        entity: 'operating system',
    },
    {
        id: 19,
        title: ['MacOS', 'MacOS'],
        description: ['Курс, нацеленный на освоение операционной системы macOS - операционной системы, разработанной компанией Apple для своих устройств. Вы научитесь работать с интерфейсом macOS, управлять файловой системой, использовать встроенные приложения и настроить систему под свои потребности. Курс также включает практические задания и советы по эффективному использованию macOS.', 'A course aimed at mastering the macOS operating system, an operating system developed by Apple for its devices. You will learn how to work with the macOS interface, manage the file system, use built-in applications, and customize the system to your needs. The course also includes hands-on activities and tips for using macOS effectively.'],
        logo: 'macos',
        discount: 0,
        queryField: 'мак макос ос oc яблоко MacOS',
        popularity: 9,
        date: 1619661600,
        entity: 'operating system',
    },

    {
        id: 20,
        title: ['Godot', 'Godot'],
        description: ['Курс, посвященный изучению движка Godot - мощного инструмента для создания игр и интерактивных приложений. Вы научитесь создавать сцены, работать с анимациями, обрабатывать пользовательский ввод и реализовывать игровую логику с использованием языка скриптования Godot. Курс также включает практические задания и примеры разработки игр с помощью Godot.', 'A course dedicated to learning the Godot engine, a powerful tool for creating games and interactive applications. You will learn how to create scenes, work with animations, process user input and implement game logic using the Godot scripting language. The course also includes hands-on activities and examples of game development with Godot.'],
        logo: 'godot',
        discount: 0,
        queryField: 'игры геймдэв gamedev Godot',
        popularity: 8,
        date: 1619575200,
        entity: 'game engine',
    },
    {
        id: 21,
        title: ['Scratch', 'Scratch'],
        description: ['Курс, ориентированный на детей и начинающих программистов, для изучения программирования с использованием популярной среды разработки Scratch. Вы научитесь создавать интерактивные и анимированные проекты, программировать события и условия, исследовать основы алгоритмического мышления. Курс также включает игровые задания и творческие проекты на основе Scratch.', 'A course aimed at children and beginner programmers to learn programming using the popular Scratch development environment. You will learn how to create interactive and animated projects, program events and conditions, explore the basics of algorithmic thinking. The course also includes games and creative projects based on Scratch.'],
        logo: 'scratch',
        discount: 0,
        queryField: 'игры геймдэв gamedev Scratch',
        popularity: 9,
        date: 1619488800,
        entity: 'programming language',
    },
    {
        id: 22,
        title: ['Perl', 'Perl'],
        description: ['Курс, охватывающий основы и продвинутые темы языка программирования Perl. Вы изучите синтаксис Perl, особенности работы с текстом и регулярными выражениями, модули и библиотеки для разработки приложений. Курс также включает практические задания и примеры использования Perl в реальных проектах.', 'A course covering the basics and advanced topics of the Perl programming language. You will learn Perl syntax, text and regular expression features, modules and libraries for application development. The course also includes practical exercises and examples of using Perl in real projects.'],
        logo: 'perl',
        discount: 0,
        queryField: 'перл верблюд бэкенд backend Perl',
        popularity: 7,
        date: 1619402400,
        entity: 'programming language',
    },
    {
        id: 23,
        title: ['Go', 'Go'],
        description: ['Курс, посвященный изучению языка программирования Go - эффективного и мощного языка для разработки приложений. Вы научитесь работать с синтаксисом Go, использовать его особенности, создавать модули и пакеты, разрабатывать высокопроизводительные приложения и веб-серверы. Курс также включает практические задания и примеры использования Go в реальных проектах.', 'A course dedicated to learning the Go programming language, an efficient and powerful language for developing applications. You will learn how to work with Go syntax, use its features, create modules and packages, develop high-performance applications and web servers. The course also includes practical tasks and examples of using Go in real projects.'],
        logo: 'golang',
        discount: 0,
        queryField: 'гоу бэкенд backend Go',
        popularity: 9,
        date: 1619316000,
        entity: 'programming language',
    },
    {
        id: 24,
        title: ['Ruby', 'Ruby'],
        description: ['Курс, нацеленный на освоение языка программирования Ruby - динамического и элегантного языка для разработки приложений. Вы научитесь работать с объектами и классами, использовать встроенные и пользовательские методы, разрабатывать веб-приложения с использованием фреймворка Ruby on Rails. Курс также включает практические задания и примеры использования Ruby в реальных проектах.', 'A course aimed at mastering the Ruby programming language, a dynamic and elegant language for developing applications. You will learn how to work with objects and classes, use built-in and custom methods, develop web applications using the Ruby on Rails framework. The course also includes practical tasks and examples of using Ruby in real projects.'],
        logo: 'ruby',
        discount: 0,
        queryField: 'рубин бэкенд backend Ruby',
        popularity: 8,
        date: 1619229600,
        entity: 'programming language',
    },
    {
        id: 25,
        title: ['Basic', 'Basic'],
        description: ['Курс, охватывающий основы и возможности языка программирования Basic. Вы изучите синтаксис Basic, работу с переменными и условиями, циклы и подпрограммы. Курс поможет вам освоить основы алгоритмического мышления и разработки программ. Курс также включает практические задания и примеры использования Basic в реальных проектах.', 'A course covering the basics and features of the Basic programming language. You will learn Basic syntax, working with variables and conditions, loops and subroutines. The course will help you master the basics of algorithmic thinking and software development. The course also includes practical tasks and examples of using Basic in real projects.'],
        logo: 'basic',
        discount: 0,
        queryField: 'басик бэйсик бэкенд backend Basic',
        popularity: 6,
        date: 1619143200,
        entity: 'programming language',
    },
    {
        id: 26,
        title: ['Assembler', 'Assembler'],
        description: ['Курс, посвященный изучению языка программирования Assembler - низкоуровневого языка, используемого для программирования на уровне машинных команд. Вы научитесь работать с регистрами, адресациями памяти, инструкциями и прерываниями процессора. Курс также включает практические задания и примеры использования Assembler в реальных проектах.', 'A course dedicated to learning the Assembler programming language - a low-level language used for programming at the level of machine instructions. You will learn how to work with registers, memory addressing, instructions, and processor interrupts. The course also includes practical tasks and examples of using Assembler in real projects.'],
        logo: 'assembly',
        discount: 0,
        queryField: 'хрень ассемблер сеембля бэкенд backend Assembler',
        popularity: 7,
        date: 1619056800,
        entity: 'programming language',
    },
    {
        id: 27,
        title: ['TypeScript', 'TypeScript'],
        description: ['Курс, посвященный изучению языка программирования TypeScript - строго типизированного расширения языка JavaScript. Вы научитесь работать с типами данных, классами, модулями, интерфейсами и другими особенностями TypeScript. Курс также включает практические задания и примеры использования TypeScript в разработке веб-приложений.', 'A course dedicated to learning the TypeScript programming language, a strongly typed extension of the JavaScript language. You will learn how to work with data types, classes, modules, interfaces, and other TypeScript features. The course also includes practical tasks and examples of using TypeScript in web application development.'],
        logo: 'typeScript',
        discount: 0,
        queryField: 'тайпскрипт фронтенд frontend TypeScript',
        popularity: 9,
        date: 1618970400,
        entity: 'programming language',
    },
    {
        id: 28,
        title: ['Angular', 'Angular'],
        description: ['Курс, нацеленный на изучение фреймворка Angular - платформы для разработки веб-приложений. Вы научитесь создавать компоненты, маршрутизацию, обработку форм, работу с HTTP-запросами и другими функциями Angular. Курс также включает практические задания и примеры разработки веб-приложений с использованием Angular.', 'A course aimed at learning the Angular framework - a platform for developing web applications. You will learn how to create components, routing, form processing, working with HTTP requests and other Angular features. The course also includes practical tasks and examples of web application development using Angular.'],
        logo: 'angular',
        discount: 0,
        queryField: 'ангулар ангуляр фронтенд frontend Angular',
        popularity: 10,
        date: 1618884000,
        entity: 'web framework',
    },
    {
        id: 29,
        title: ['Vue.js', 'Vue.js'],
        description: ['Курс, посвященный изучению фреймворка Vue.js - прогрессивной JavaScript-библиотеки для создания пользовательских интерфейсов. Вы научитесь создавать компоненты, управлять состоянием, реактивно отслеживать изменения и работать с маршрутизацией в Vue.js. Курс также включает практические задания и примеры разработки веб-приложений с использованием Vue.js.', 'A course dedicated to learning the Vue.js framework, a progressive JavaScript library for building user interfaces. You will learn how to create components, manage state, reactively track changes, and work with routing in Vue.js. The course also includes practical tasks and examples of web application development using Vue.js.'],
        logo: 'vue',
        discount: 0,
        queryField: 'вьюжс вьюджс вуджс вужс фронтенд frontend джс Vue.js Vuejs',
        popularity: 9,
        date: 1618797600,
        entity: 'web framework',
    },
    {
        id: 30,
        title: ['Adobe Photoshop', 'Adobe Photoshop'],
        description: ['Курс, нацеленный на освоение профессионального графического редактора Adobe Photoshop. Вы научитесь работать с инструментами редактирования изображений, создавать эффекты, корректировать цвета и тон, ретушировать фотографии и многое другое. Курс также включает практические задания и примеры использования Photoshop для создания графических проектов.', "A course aimed at mastering the professional graphics editor Adobe Photoshop. You'll learn how to work with image editing tools, create effects, adjust colors and tone, retouch photos, and more. The course also includes practical tasks and examples of using Photoshop to create graphic projects."],
        logo: 'photoshop',
        discount: 0,
        queryField: 'Adobe Photoshop адобе фотошоп Adobe Photoshop',
        popularity: 10,
        date: 1618711200,
        entity: 'software',
    },
    {
        id: 31,
        title: ['Adobe After Effects', 'Adobe After Effects'],
        description: ['Курс, посвященный изучению программы Adobe After Effects - программы для создания и редактирования видеоэффектов и анимации. Вы научитесь создавать анимированные композиции, добавлять визуальные эффекты, работать с ключевыми кадрами и трекингом движения. Курс также включает практические задания и примеры создания видеоэффектов с использованием After Effects.', 'A course dedicated to the study of Adobe After Effects - a program for creating and editing video effects and animation. You will learn how to create animated compositions, add visual effects, work with keyframes and motion tracking. The course also includes hands-on activities and examples of creating video effects using After Effects.'],
        logo: 'after_effects',
        discount: 0,
        queryField: 'видео афтер эффект адобе Adobe After Effects',
        popularity: 9,
        date: 1618624800,
        entity: 'software',
    },
    {
        id: 32,
        title: ['Adobe Premiere Pro', 'Adobe Premiere Pro'],
        description: ['Курс, нацеленный на освоение программы Adobe Premiere Pro - профессионального видеоредактора. Вы научитесь монтировать видео, добавлять переходы, эффекты и аудио, работать с цветокоррекцией и таймлайном. Курс также включает практические задания и примеры создания и редактирования видеоматериалов с использованием Premiere Pro.', 'A course aimed at mastering the Adobe Premiere Pro program - a professional video editor. You will learn how to edit video, add transitions, effects and audio, work with color correction and timeline. The course also includes hands-on activities and examples of creating and editing video using Premiere Pro.'],
        logo: 'premiere-pro',
        discount: 0,
        queryField: 'видео премиер премйер про адобе Adobe Premiere Pro',
        popularity: 9,
        date: 1618538400,
        entity: 'software',
    },
    {
        id: 33,
        title: ['SCSS', 'SCSS'],
        description: ['Курс, охватывающий язык стилей SCSS - расширение языка CSS. Вы научитесь создавать структурированные и модульные стили, использовать переменные, миксины, функции и другие возможности SCSS. Курс поможет вам улучшить процесс стилизации веб-приложений и веб-сайтов.', 'A course covering the SCSS style language, an extension of the CSS language. You will learn how to create structured and modular styles, use variables, mixins, functions and other features of SCSS. The course will help you improve the process of styling web applications and websites.'],
        logo: 'scss',
        discount: 0,
        queryField: 'sas cass сас сксс SCSS',
        popularity: 8,
        date: 1618452000,
        entity: 'styling language',
    },
    {
        id: 34,
        title: ['Верстка', 'Layout'],
        description: ['Курс, ориентированный на освоение основ верстки веб-страниц. Вы научитесь создавать семантическую разметку с использованием HTML, задавать стили с помощью CSS, работать с макетами и адаптивностью, использовать различные инструменты и техники для создания качественных веб-страниц. Курс также включает практические задания и примеры верстки реальных веб-страниц.', 'A course focused on mastering the basics of web page layout. You will learn how to create semantic markup using HTML, style using CSS, work with layouts and responsiveness, use various tools and techniques to create high-quality web pages. The course also includes practical tasks and examples of layout of real web pages.'],
        logo: 'web-development',
        discount: 0,
        queryField: 'верстка layout фронтенд frontend',
        popularity: 10,
        date: 1618365600,
        entity: 'profession',
    },
    {
        id: 35,
        title: ['C', 'C'],
        description: ['Курс, посвященный изучению языка программирования C - мощного и универсального языка для системного программирования. Вы научитесь работать с переменными, операторами, условиями, циклами и функциями на языке C. Курс также включает практические задания и примеры использования языка C в разработке программ.', 'A course dedicated to learning the C programming language - a powerful and versatile language for system programming. You will learn how to work with variables, operators, conditions, loops and functions in the C language. The course also includes practical tasks and examples of using the C language in program development.'],
        logo: 'c',
        discount: 0,
        queryField: 'си с бэкенд backend программирование C',
        popularity: 9,
        date: 1618279200,
        entity: 'programming language',
    },
    {
        id: 36,
        title: ['C#', 'C#'],
        description: ['Курс, нацеленный на освоение языка программирования C# - языка разработки приложений на платформе .NET. Вы научитесь создавать классы, работать с объектами, использовать наследование, полиморфизм и другие особенности C#. Курс также включает практические задания и примеры разработки приложений с использованием C#.', 'A course aimed at mastering the C# programming language - the language for developing applications on the .NET platform. You will learn how to create classes, work with objects, use inheritance, polymorphism and other C# features. The course also includes practical tasks and examples of application development using C#.'],
        logo: 'csharp',
        discount: 0,
        queryField: 'сишарп си# с# сшарп бэкенд backend программирование C#',
        popularity: 10,
        date: 1618192800,
        entity: 'programming language',
    },
    {
        id: 37,
        title: ['React', 'React'],
        description: ['Курс, нацеленный на изучение библиотеки React - популярного инструмента для разработки пользовательских интерфейсов. Вы научитесь создавать компоненты, управлять состоянием, работать с маршрутизацией и другими функциями React. Курс также включает практические задания и примеры разработки веб-приложений с использованием React.', 'A course aimed at learning the React library, a popular tool for developing user interfaces. You will learn how to create components, manage state, work with routing and other React features. The course also includes practical tasks and examples of web application development using React.'],
        logo: 'react',
        discount: 0,
        queryField: 'реакт фронтенд frontend джава джаваскрипт жава жаваскрипт React',
        popularity: 10,
        date: 1618106400,
        entity: 'JavaScript library',
    },
    {
        id: 38,
        title: ['Pascal', 'Pascal'],
        description: ['Курс, посвященный изучению языка программирования Pascal - языка, пригодного для обучения основам программирования. Вы научитесь работать с переменными, операторами, циклами, условиями и процедурами на языке Pascal. Курс также включает практические задания и примеры разработки программ на языке Pascal.', 'A course dedicated to the study of the Pascal programming language - a language suitable for teaching the basics of programming. You will learn how to work with variables, operators, loops, conditions and procedures in Pascal. The course also includes practical tasks and examples of developing programs in Pascal.'],
        logo: 'pascal',
        discount: 0,
        queryField: 'паскаль программирование бэкенд backend Pascal',
        popularity: 7,
        date: 1618020000,
        entity: 'programming language',
    },
    {
        id: 39,
        title: ['Java', 'Java'],
        description: ['Курс, нацеленный на освоение языка программирования Java - универсального языка для создания приложений. Вы научитесь работать с классами, объектами, наследованием, полиморфизмом, обработкой исключений и другими возможностями Java. Курс также включает практические задания и примеры разработки приложений на языке Java.', 'A course aimed at mastering the Java programming language - a universal language for creating applications. You will learn to work with classes, objects, inheritance, polymorphism, exception handling, and other Java features. The course also includes practical tasks and examples of application development in the Java language.'],
        logo: 'java',
        discount: 0,
        queryField: ' джава жава программирование бэкенд backend Java',
        popularity: 10,
        date: 1617933600,
        entity: 'programming language',
    },
    {
        id: 40,
        title: ['Unreal Engine', 'Unreal Engine'],
        description: ['Курс, нацеленный на изучение движка Unreal Engine - мощного инструмента для создания игр и визуализации. Вы научитесь создавать сцены, работать с материалами, анимациями, физикой, светом и другими функциями Unreal Engine. Курс также включает практические задания и примеры разработки игровых проектов с использованием Unreal Engine.', 'A course aimed at learning the Unreal Engine, a powerful tool for creating games and visualization. You will learn how to create scenes, work with materials, animations, physics, light and other features of Unreal Engine. The course also includes practical tasks and examples of developing game projects using the Unreal Engine.'],
        logo: 'unreal-engine',
        discount: 0,
        queryField: 'игры геймдэв gamedev анреал анриал Unreal Engine',
        popularity: 9,
        date: 1617847200,
        entity: 'game development',
    },
    {
        id: 41,
        title: ['Unity', 'Unity'],
        description: ['Курс, посвященный изучению движка Unity - популярного инструмента для разработки игр. Вы научитесь создавать сцены, работать с объектами, анимациями, физикой, светом и другими возможностями Unity. Курс также включает практические задания и примеры разработки игровых проектов с использованием Unity.', 'A course dedicated to learning the Unity engine, a popular tool for game development. You will learn how to create scenes, work with objects, animations, physics, light and other Unity features. The course also includes practical tasks and examples of developing game projects using Unity.'],
        logo: 'unity',
        discount: 0,
        queryField: 'игры геймдэв gamedev юнити Unity',
        popularity: 10,
        date: 1617760800,
        entity: 'game development',
    },
    {
        id: 42,
        title: ['Git', 'Git'],
        description: ['Курс, нацеленный на освоение системы контроля версий Git - популярного инструмента для управления и отслеживания изменений в коде. Вы научитесь создавать репозитории, ветки, коммиты, слияния и работать с удаленными репозиториями. Курс также включает практические задания и примеры использования Git в разработке программного обеспечения.', 'A course aimed at mastering the Git version control system, a popular tool for managing and tracking changes in code. You will learn how to create repositories, branches, commits, merges and work with remote repositories. The course also includes practical tasks and examples of using Git in software development.'],
        logo: 'git',
        discount: 0,
        queryField: 'контроль версий гитхаб Git',
        popularity: 10,
        date: 1617674400,
        entity: 'version control system',
    },
    {
        id: 43,
        title: ['Использование виртуальных машин', 'Using virtual machines'],
        description: ['Курс, охватывающий основы использования виртуальных машин - виртуальных компьютеров, работающих на физической машине. Вы научитесь создавать, настраивать и управлять виртуальными машинами, а также использовать их для различных задач, включая тестирование программного обеспечения и развертывание серверов.', "A course covering the basics of using virtual machines - virtual computers running on a physical machine. You'll learn how to create, configure, and manage virtual machines, and how to use them for a variety of tasks, including software testing and server deployment."],
        logo: 'VM',
        discount: 0,
        queryField: 'VM Использование виртуальных машин Using virtual machines',
        popularity: 8,
        date: 1617588000,
        entity: 'virtualization',
    },
    {
        id: 44,
        title: ['Основы машинного обучения', 'Fundamentals of machine learning'],
        description: ['Курс, охватывающий основы машинного обучения - области искусственного интеллекта, которая изучает методы и алгоритмы, позволяющие компьютеру обучаться на основе данных и делать прогнозы или принимать решения. Вы научитесь работать с различными моделями машинного обучения, обрабатывать и анализировать данные, и создавать простые прогнозные модели.', 'A course covering the fundamentals of machine learning, a field of artificial intelligence that studies methods and algorithms that allow a computer to learn from data and make predictions or make decisions. You will learn how to work with various machine learning models, process and analyze data, and create simple predictive models.'],
        logo: 'machine_learning',
        discount: 0,
        queryField: 'ии ai Основы машинного обучения Fundamentals of machine learning',
        popularity: 9,
        date: 1617501600,
        entity: 'machine learning',
    },
    {
        id: 45,
        title: ['Криптография', 'Cryptography'],
        description: ['Курс, охватывающий основы криптографии - науки об защите информации с использованием шифрования и других методов. Вы изучите различные методы шифрования, протоколы безопасности, цифровые подписи и другие аспекты криптографии. Курс также включает практические задания и примеры применения криптографии в реальных сценариях.', 'A course covering the basics of cryptography - the science of protecting information using encryption and other methods. You will learn various encryption methods, security protocols, digital signatures, and other aspects of cryptography. The course also includes practical tasks and examples of cryptography in real life scenarios.'],
        logo: 'criptograf',
        discount: 0,
        queryField: 'шифрование Криптография Cryptography',
        popularity: 9,
        date: 1617415200,
        entity: 'cryptography',
    },
    {
        id: 46,
        title: ['Django', 'Django'],
        description: ['Курс, посвященный изучению Django - фреймворка для разработки веб-приложений на языке Python. Вы научитесь создавать мощные и масштабируемые веб-приложения, работать с базами данных, обрабатывать формы, управлять аутентификацией и авторизацией пользователей. Курс включает практические задания и примеры разработки веб-приложений с использованием Django.', 'A course dedicated to learning Django, a framework for developing web applications in Python. You will learn how to create powerful and scalable web applications, work with databases, process forms, manage user authentication and authorization. The course includes practical tasks and examples of web application development using Django.'],
        logo: 'python_django',
        discount: 0,
        queryField: 'джанго питон программирование бэкенд backend Django',
        popularity: 9,
        date: 1617415200,
        entity: 'web development',
    },
    {
        id: 47,
        title: ['Flask', 'Flask'],
        description: ['Курс, посвященный изучению Flask - легковесного фреймворка для разработки веб-приложений на языке Python. Вы научитесь создавать веб-страницы, обрабатывать запросы, работать с базами данных, управлять сессиями и другими функциями Flask. Курс также включает практические задания и примеры разработки веб-приложений с использованием Flask.', 'A course dedicated to learning Flask, a lightweight framework for developing web applications in Python. You will learn how to create web pages, process requests, work with databases, manage sessions and other Flask features. The course also includes practical tasks and examples of developing web applications using Flask.'],
        logo: 'flask',
        discount: 0,
        queryField: 'фласк Flask',
        popularity: 8,
        date: 1617328800,
        entity: 'web development',
    },
    {
        id: 50,
        title: ['Создание телеграмм ботов', 'Creation of telegram bots'],
        description: ['Курс, нацеленный на обучение созданию ботов для популярной мессенджер-платформы Telegram. Вы научитесь использовать Telegram Bot API, создавать и настраивать ботов, обрабатывать сообщения и команды от пользователей. Курс также включает практические задания и примеры разработки телеграмм ботов на различных языках программирования.', 'A course aimed at learning how to create bots for the popular Telegram messenger platform. You will learn how to use the Telegram Bot API, create and configure bots, process messages and commands from users. The course also includes practical tasks and examples of developing telegram bots in various programming languages.'],
        logo: 'telegtam_bot',
        discount: 0,
        queryField: 'боты телеграм Создание телеграмм ботов Creation of telegram bots',
        popularity: 7,
        date: 1617156000,
        entity: 'messaging platform',
    },
    {
        id: 51,
        title: ['Создание дискорд ботов', 'Creating Discord Bots'],
        description: ['Курс, посвященный созданию ботов для популярной платформы общения Discord. Вы научитесь использовать Discord API, создавать и настраивать ботов, обрабатывать сообщения, управлять серверами и каналами. Курс также включает практические задания и примеры разработки дискорд ботов на различных языках программирования.', 'A course dedicated to creating bots for the popular communication platform Discord. You will learn how to use the Discord API, create and configure bots, process messages, manage servers and channels. The course also includes practical tasks and examples of developing discord bots in various programming languages.'],
        logo: 'discordbot',
        discount: 0,
        queryField: 'боты дискорд Создание дискорд ботов Creating Discord Bots',
        popularity: 8,
        date: 1617069600,
        entity: 'communication platform',
    },
    {
        id: 52,
        title: ['Создание вк ботов', 'Creating VK bots'],
        description: ['Курс, нацеленный на обучение созданию ботов для популярной социальной сети ВКонтакте. Вы научитесь использовать VK API, создавать и настраивать ботов, обрабатывать сообщения, управлять группами и пользователями. Курс также включает практические задания и примеры разработки вк ботов на различных языках программирования.', 'A course aimed at learning how to create bots for the popular social network VKontakte. You will learn how to use the VK API, create and configure bots, process messages, manage groups and users. The course also includes practical tasks and examples of developing VK bots in various programming languages.'],
        logo: 'vkbot',
        discount: 0,
        queryField: 'боты контакт Создание вк ботов Creating VK bots',
        popularity: 7,
        date: 1616983200,
        entity: 'social network',
    },
    {
        id: 53,
        title: ['Работа с командной строкой Windows', 'Working with the Windows command line'],
        description: ['Курс, нацеленный на освоение работы с командной строкой Windows. Вы научитесь использовать команды и утилиты командной строки для выполнения различных задач, управления файлами и папками, настройки системы, администрирования компьютера и других операций. Курс также включает практические задания и примеры работы с командной строкой Windows.', 'A course aimed at mastering the work with the Windows command line. You will learn how to use command line commands and utilities to perform various tasks, manage files and folders, configure the system, administer the computer, and more. The course also includes practical tasks and examples of working with the Windows command line.'],
        logo: 'cmd',
        discount: 0,
        queryField: 'Работа с командной строкой Windows Working with the Windows command line',
        popularity: 9,
        date: 1616896800,
        entity: 'Windows',
    },
    {
        id: 54,
        title: ['Общий курс математики для программистов', 'Course of mathematics for programmers'],
        description: ['Курс, охватывающий основы математики, важные для программистов. Вы изучите основные математические концепции, такие как алгебра, тригонометрия, дискретная математика, логика, анализ данных и другие. Курс поможет вам лучше понять и применять математические аспекты в программировании и разработке.', 'A course covering the fundamentals of mathematics important to programmers. You will learn basic mathematical concepts such as algebra, trigonometry, discrete mathematics, logic, data analysis and others. The course will help you better understand and apply mathematical aspects in programming and development.'],
        logo: 'math',
        discount: 0,
        queryField: 'Общий курс математики для программистов Course of mathematics for programmers',
        popularity: 8,
        date: 1616810400,
        entity: 'mathematics',
    },
    {
        id: 55,
        title: ['Геометрия для создания игр и виртуальных миров', 'Geometry for creating games and virtual worlds'],
        description: ['Курс, направленный на изучение геометрии и ее применение в создании игр и виртуальных миров. Вы изучите основные геометрические принципы, трехмерную геометрию, трансформации объектов, коллизии и другие аспекты, важные для разработки игровых приложений и виртуальной реальности.', 'A course aimed at studying geometry and its application in the creation of games and virtual worlds. You will learn basic geometric principles, 3D geometry, object transformations, collisions and other aspects important for the development of game applications and virtual reality.'],
        logo: 'geometry',
        discount: 0,
        queryField: 'Геометрия для создания игр и виртуальных миров Geometry for creating games and virtual worlds',
        popularity: 7,
        date: 1616724000,
        entity: 'geometry',
    },
    {
        id: 56,
        title: ['Курсы графического дизайна', 'Graphic design courses'],
        description: ['Набор курсов, посвященных изучению графического дизайна. Вы научитесь работать с графическими инструментами, создавать логотипы, иллюстрации, веб-дизайн, управлять цветами и композицией. Курсы также включают практические задания и примеры работы с различными графическими проектами.', 'A set of courses dedicated to the study of graphic design. You will learn how to work with graphic tools, create logos, illustrations, web design, manage colors and composition. The courses also include practical tasks and examples of working with various graphic projects.'],
        logo: 'design',
        discount: 0,
        queryField: 'Курсы графического дизайна Graphic design courses',
        popularity: 8,
        date: 1616637600,
        entity: 'graphic design',
    },
    {
        id: 57,
        title: ['Разработкич Игр', 'Game Developer'],
        description: ['Курс, предназначенный для тех, кто хочет стать профессиональным разработчиком игр. Вы изучите основные принципы и технологии разработки игр, включая движки, программирование игровой логики, создание графики и звука, управление ресурсами и другие аспекты, важные для успешной карьеры в индустрии разработки игр.', 'A course designed for those who want to become a professional game developer. You will learn the fundamental principles and technologies of game development, including engines, game logic programming, graphics and sound creation, resource management, and other aspects that are important for a successful career in the game development industry.'],
        logo: 'gamedev',
        discount: 0,
        queryField: 'геймдэв игры gamedev Разработкич Игр Game Developer',
        popularity: 9,
        date: 1616551200,
        entity: 'game development',
    },
    {
        id: 58,
        title: ['Парсинг', 'Parsing'],
        description: ['Курс, посвященный изучению парсинга - процессу извлечения и анализа данных с веб-сайтов. Вы научитесь использовать различные инструменты и библиотеки для парсинга данных, обрабатывать HTML-страницы, извлекать информацию, автоматизировать задачи сбора данных. Курс также включает практические задания и примеры парсинга данных с реальных веб-сайтов.', 'A course dedicated to the study of scraping - the process of extracting and analyzing data from websites. You will learn how to use various tools and libraries for data parsing, process HTML pages, extract information, automate data collection tasks. The course also includes practical tasks and examples of data parsing from real websites.'],
        logo: 'parsing',
        discount: 0,
        queryField: 'Парсинг Parsing',
        popularity: 7,
        date: 1616464800,
        entity: 'data processing',
    },
    {
        id: 59,
        title: ['Работа с сетями', 'Working with networks'],
        description: ['Курс, нацеленный на освоение работы с компьютерными сетями. Вы изучите основные протоколы и технологии сетевого взаимодействия, настройку и управление сетевыми устройствами, администрирование сетей, безопасность и другие аспекты работы с сетями. Курс также включает практические задания и примеры работы с компьютерными сетями.', 'A course aimed at mastering the work with computer networks. You will learn the basic protocols and technologies of networking, configuring and managing network devices, network administration, security and other aspects of working with networks. The course also includes practical tasks and examples of working with computer networks.'],
        logo: 'netWork',
        discount: 0,
        queryField: 'сети Работа с сетями Working with networks',
        popularity: 8,
        date: 1616378400,
        entity: 'networking',
    },
    {
        id: 60,
        title: ['Устройство работы компьютера', 'The device of the computer'],
        description: ['Курс, посвященный изучению устройства и принципов работы компьютера. Вы изучите аппаратные компоненты компьютера, принципы работы процессора, памяти, жестких дисков, сетевых устройств и других компонентов. Курс поможет вам лучше понять внутреннее устройство компьютера и его взаимодействие с программным обеспечением.', 'A course devoted to the study of the device and principles of computer operation. You will learn the hardware components of a computer, how the processor, memory, hard drives, network devices, and other components work. The course will help you better understand the internal workings of a computer and how it interacts with software.'],
        logo: 'computer-pc',
        discount: 0,
        queryField: 'Устройство работы компьютера The device of the computer',
        popularity: 9,
        date: 1616292000,
        entity: 'computer hardware',
    },
    {
        id: 61,
        title: ['Arduino', 'Arduino'],
        description: ['Курс, нацеленный на изучение Arduino - платформы для создания интерактивных электронных устройств. Вы научитесь программировать Arduino, работать с датчиками и модулями, создавать простые электронные схемы и управлять устройствами через различные интерфейсы. Курс также включает практические задания и примеры разработки на Arduino.', 'A course aimed at learning Arduino - a platform for creating interactive electronic devices. You will learn how to program Arduino, work with sensors and modules, create simple electronic circuits and control devices through various interfaces. The course also includes hands-on activities and examples of Arduino development.'],
        logo: 'arduino',
        discount: 0,
        queryField: 'ардуино роботы Arduino',
        popularity: 8,
        date: 1616205600,
        entity: 'Arduino',
    },
    {
        id: 62,
        title: ['Raspberry Pi', 'Raspberry Pi'],
        description: ['Курс, посвященный изучению Raspberry Pi - маленького одноплатного компьютера. Вы научитесь работать с Raspberry Pi, устанавливать операционную систему, подключать периферийные устройства, создавать простые проекты, используя возможности Raspberry Pi. Курс также включает практические задания и примеры разработки на Raspberry Pi.', 'A course dedicated to the study of Raspberry Pi - a small single-board computer. You will learn how to work with the Raspberry Pi, install the operating system, connect peripherals, create simple projects using the capabilities of the Raspberry Pi. The course also includes hands-on activities and examples of Raspberry Pi development.'],
        logo: 'raspberry',
        discount: 0,
        queryField: 'ардуино роботы расберри распберри Raspberry Pi',
        popularity: 7,
        date: 1616119200,
        entity: 'raspberry Pi',
    },
    {
        id: 63,
        title: ['Теория вероятностей', 'Probability theory'],
        description: ['Курс, охватывающий основы теории вероятностей - математической дисциплины, изучающей случайные явления и вероятности их возникновения. Вы изучите основные понятия, законы и методы теории вероятностей, а также их применение в различных областях, включая статистику и машинное обучение.', 'A course covering the basics of probability theory - a mathematical discipline that studies random phenomena and the probabilities of their occurrence. You will learn the basic concepts, laws and methods of probability theory, as well as their application in various fields, including statistics and machine learning.'],
        logo: 'Theory_Veroit',
        discount: 0,
        queryField: 'математика Теория вероятностей Probability theory',
        popularity: 8,
        date: 1616032800,
        entity: 'mathematics',
    },
    {
        id: 64,
        title: ['Пентестинг', 'Pentesting'],
        description: ['Курс, посвященный пентестингу - процессу проверки безопасности компьютерных систем и сетей путем поиска уязвимостей и эксплуатации их для получения несанкционированного доступа. Вы изучите основные методы и инструменты пентестинга, этические аспекты и правовые вопросы, а также научитесь проводить практические тестирования безопасности.', 'A course dedicated to pentesting - the process of checking the security of computer systems and networks by searching for vulnerabilities and exploiting them to gain unauthorized access. You will learn the basic methods and tools of pentesting, ethical aspects and legal issues, as well as how to conduct practical security testing.'],
        logo: 'Pentest',
        discount: 0,
        queryField: 'Пентестинг Pentesting',
        popularity: 9,
        date: 1615946400,
        entity: 'security',
    },
    {
        id: 65,
        title: ['API', 'API'],
        description: ['Курс, посвященный изучению API (Application Programming Interface) - интерфейсов, предоставляемых программными системами для взаимодействия с другими приложениями. Вы изучите основные концепции и принципы работы с API, научитесь использовать и интегрировать API различных сервисов и платформ для разработки приложений.', 'A course devoted to the study of API (Application Programming Interface) - interfaces provided by software systems for interacting with other applications. You will learn the basic concepts and principles of working with APIs, learn how to use and integrate the APIs of various services and platforms for developing applications.'],
        logo: 'api',
        discount: 0,
        queryField: 'апи API',
        popularity: 8,
        date: 1615860000,
        entity: 'API',
    },
    {
        id: 66,
        title: ['Интернет протоколы', 'Internet protocols'],
        description: ['Курс, посвященный изучению интернет протоколов - стандартных правил и процедур, определяющих передачу данных в компьютерных сетях. Вы изучите основные протоколы, такие как TCP/IP, HTTP, SMTP, FTP, DNS и другие, их структуру, функциональность и применение. Курс поможет вам лучше понять принципы работы интернета и взаимодействие между компьютерами.', 'A course dedicated to the study of Internet protocols - standard rules and procedures that determine the transmission of data in computer networks. You will learn the basic protocols such as TCP/IP, HTTP, SMTP, FTP, DNS and others, their structure, functionality and application. The course will help you better understand the principles of the Internet and the interaction between computers.'],
        logo: 'tcp_ip',
        discount: 0,
        queryField: 'Интернет протоколы Internet protocols',
        popularity: 9,
        date: 1615773600,
        entity: 'networking',
    },
    {
        id: 67,
        title: ['Алгебра логики', 'Algebra of logic'],
        description: ['Курс, посвященный изучению алгебры логики - математической дисциплины, изучающей формальные структуры и операции логического вывода. Вы изучите основные понятия и законы алгебры логики, логические функции, методы доказательства и применение логических операций в информатике и вычислительной технике.', 'A course dedicated to the study of the algebra of logic - a mathematical discipline that studies the formal structures and operations of inference. You will learn the basic concepts and laws of the algebra of logic, logical functions, methods of proof and the application of logical operations in computer science and computer technology.'],
        logo: 'mathematical-logic',
        discount: 0,
        queryField: 'математика Алгебра логики Algebra of logic',
        popularity: 7,
        date: 1615687200,
        entity: 'mathematics',
    },
    {
        id: 68,
        title: ['Теория графов', 'Graph theory'],
        description: ['Курс, посвященный изучению теории графов - математической дисциплины, изучающей свойства и применение графовых структур. Вы изучите основные понятия и алгоритмы теории графов, такие как поиск кратчайшего пути, минимальное остовное дерево, топологическая сортировка и другие, их применение в различных областях, включая компьютерные науки и логистику.', 'A course dedicated to the study of graph theory - a mathematical discipline that studies the properties and applications of graph structures. You will learn the basic concepts and algorithms of graph theory, such as finding the shortest path, minimum spanning tree, topological sort and others, their application in various fields, including computer science and logistics.'],
        logo: 'graph',
        discount: 0,
        queryField: 'математика Теория графов Graph theory',
        popularity: 8,
        date: 1615600800,
        entity: 'mathematics',
    },
    {
        id: 69,
        title: ['История программирования', 'History of programming'],
        description: ['Курс, охватывающий историю развития программирования и вычислительной техники. Вы изучите основные этапы и вехи истории программирования, познакомитесь с важными персонами и их вкладом в развитие отрасли, а также рассмотрите основные технологии и языки программирования, с которыми сталкивались разработчики на протяжении времени.', "A course covering the history of the development of programming and computing. You'll explore major milestones and milestones in the history of programming, meet important people and their contributions to the industry, and review the major technologies and programming languages that developers have encountered over time."],
        logo: 'history',
        discount: 0,
        queryField: 'История программирования History of programming',
        popularity: 7,
        date: 1615514400,
        entity: 'programming',
    },
    {
        id: 70,
        title: ['Продвинутый CSS', 'Advanced CSS'],
        description: ['Курс, нацеленный на более глубокое изучение CSS (Cascading Style Sheets) - языка описания внешнего вида веб-страниц. Вы изучите продвинутые техники и возможности CSS, включая работу с анимацией, трансформациями, медиа-запросами, адаптивным дизайном и другими аспектами, позволяющими создавать более сложные и интерактивные веб-интерфейсы.', "A course aimed at a deeper study of CSS (Cascading Style Sheets) - a language for describing the appearance of web pages. You'll learn advanced CSS techniques and capabilities, including working with animations, transforms, media queries, responsive design, and more to create more complex and interactive web experiences."],
        logo: 'Vcss',
        discount: 0,
        queryField: 'sas cass сас сксс Продвинутый CSS Advanced CSS',
        popularity: 8,
        date: 1615428000,
        entity: 'web development',
    },
    {
        id: 71,
        title: ['Redux', 'Redux'],
        description: ['Курс, посвященный изучению Redux - библиотеки для управления состоянием приложения в JavaScript. Вы изучите основные концепции и принципы работы Redux, поймете, как организовать и управлять состоянием приложения, разделять логику и представление данных, и использовать Redux в сочетании с React и другими фреймворками.', 'A course dedicated to learning Redux, a library for managing application state in JavaScript. You will learn the basic concepts and principles of Redux, understand how to organize and manage application state, separate logic and data representation, and use Redux in combination with React and other frameworks.'],
        logo: 'redux',
        discount: 0,
        queryField: 'редукс backend бэкенд Redux',
        popularity: 7,
        date: 1615341600,
        entity: 'web development',
    },
    {
        id: 72,
        title: ['React разработчик', 'React developer'],
        description: ['Курс, нацеленный на изучение React - JavaScript библиотеки для создания пользовательских интерфейсов. Вы освоите основные концепции и принципы работы React, научитесь создавать компоненты, управлять состоянием приложения, обрабатывать события и взаимодействовать с сервером. Курс также включает практические задания и разработку реальных проектов на React.', 'A course aimed at learning React - a JavaScript library for creating user interfaces. You will master the basic concepts and principles of React, learn how to create components, manage application state, handle events and interact with the server. The course also includes practical tasks and development of real projects on React.'],
        logo: 'react',
        discount: 0,
        queryField: 'реакт фронтенд frontend джава джаваскрипт жава жаваскрипт React разработчик developer',
        popularity: 9,
        date: 1615255200,
        entity: 'web development',
    },
    {
        id: 73,
        title: ['Data Science', 'Data Science'],
        description: ['Курс, посвященный изучению Data Science - области науки о данных, объединяющей статистику, машинное обучение и анализ данных. Вы изучите основные методы и инструменты Data Science, научитесь работать с большими объемами данных, проводить исследовательский анализ, строить модели прогнозирования и применять машинное обучение для решения задач анализа данных.', 'A course dedicated to the study of Data Science - a field of data science that combines statistics, machine learning and data analysis. You will learn the basic methods and tools of Data Science, how to work with large amounts of data, conduct exploratory analysis, build predictive models and apply machine learning to solve data analysis problems.'],
        logo: 'data-science',
        queryField: 'дата саенс дата сайнс питон Data Science',
        discount: 0,
        popularity: 9,
        date: 1615168800,
        entity: 'data science',
    },
    {
        id: 74,
        title: ['1C', '1C'],
        description: ['Курс, посвященный изучению платформы 1C:Enterprise - популярной системы автоматизации управленческого и бухгалтерского учета. Вы научитесь создавать информационные базы, проектировать и настраивать конфигурации, разрабатывать прикладные решения и администрировать систему 1C. Курс также включает практические задания и примеры работы с платформой 1C.', 'A course dedicated to the study of the 1C:Enterprise platform - a popular management and accounting automation system. You will learn how to create infobases, design and configure configurations, develop application solutions and administer the 1C system. The course also includes practical tasks and examples of working with the 1C platform.'],
        logo: '1c',
        discount: 0,
        queryField: '1c 1с 1C',
        popularity: 7,
        date: 1615082400,
        entity: '1C:Enterprise',
    },
    {
        id: 75,
        title: ['Swift', 'Swift'],
        description: ['Курс, посвященный изучению Swift - языка программирования, разработанным компанией Apple для создания приложений под iOS, macOS, watchOS и tvOS. Вы изучите основные концепции и синтаксис языка Swift, научитесь создавать приложения для мобильных и десктопных платформ Apple, работать с фреймворками и инструментами разработки.', 'A course dedicated to learning Swift, a programming language developed by Apple for creating applications for iOS, macOS, watchOS and tvOS. You will learn the basic concepts and syntax of the Swift language, learn how to create applications for Apple mobile and desktop platforms, work with frameworks and development tools.'],
        logo: 'swift',
        discount: 0,
        queryField: 'свифт Swift',
        popularity: 8,
        date: 1614996000,
        entity: 'programming',
    },
    {
        id: 76,
        title: ['Kotlin', 'Kotlin'],
        description: ['Курс, посвященный изучению Kotlin - статически типизированного языка программирования, совместимого с Java, разработанным компанией JetBrains. Вы изучите основные концепции и возможности языка Kotlin, научитесь создавать приложения для платформы Android, работать с Java-кодом, использовать функциональные возможности языка и фреймворки разработки.', 'A course dedicated to learning Kotlin, a statically typed Java-compatible programming language developed by JetBrains. You will learn the basic concepts and features of the Kotlin language, learn how to create applications for the Android platform, work with Java code, use the functionality of the language and development frameworks.'],
        logo: 'kotlin',
        discount: 0,
        queryField: 'котлин котлен Kotlin',
        popularity: 9,
        date: 1614909600,
        entity: 'programming',
    },
    {
        id: 77,
        title: ['Scala', 'Scala'],
        description: ['Курс, посвященный изучению Scala - многопарадигменного языка программирования, совместимого с Java, разработанного для создания масштабируемых и надежных приложений. Вы изучите основные концепции и возможности языка Scala, научитесь работать с функциональным и объектно-ориентированным программированием, разрабатывать приложения для Java Virtual Machine (JVM) и использовать фреймворки разработки.', 'A course dedicated to learning Scala, a Java-compatible multi-paradigm programming language designed to build scalable and robust applications. You will learn the basic concepts and features of the Scala language, learn how to work with functional and object-oriented programming, develop applications for the Java Virtual Machine (JVM), and use development frameworks.'],
        logo: 'scala',
        discount: 0,
        queryField: 'скала дувейн джонсон база данных Scala',
        popularity: 8,
        date: 1614823200,
        entity: 'programming',
    },
    {
        id: 78,
        title: ['React Native', 'React Native'],
        description: ['Курс, посвященный изучению React Native - фреймворка для разработки мобильных приложений под iOS и Android с использованием JavaScript и React. Вы изучите основные концепции и возможности React Native, научитесь создавать переносимые и эффективные мобильные приложения, работать с компонентами, навигацией, асинхронными запросами и другими аспектами разработки.', 'A course dedicated to learning React Native - a framework for developing mobile applications for iOS and Android using JavaScript and React. You will learn the basic concepts and features of React Native, learn how to create portable and efficient mobile applications, work with components, navigation, asynchronous requests and other aspects of development.'],
        logo: 'react-native',
        discount: 0,
        queryField: 'реакт наитев реакт-найтив реакт найтив React Native',
        popularity: 9,
        date: 1614736800,
        entity: 'mobile development',
    },
    {
        id: 79,
        title: ['Lua', 'Lua'],
        description: ['Курс, посвященный изучению языка программирования Lua - легковесного и гибкого языка, широко используемого в различных областях, включая игровую разработку и расширение приложений. Вы изучите основные концепции и синтаксис языка Lua, научитесь создавать сценарии, взаимодействовать с другими языками программирования и использовать Lua в своих проектах.', 'A course dedicated to learning the Lua programming language, a lightweight and flexible language widely used in various fields, including game development and application extension. You will learn the basic concepts and syntax of the Lua language, learn how to script, interact with other programming languages, and use Lua in your projects.'],
        logo: 'lua',
        discount: 0,
        queryField: 'лиа луа Lua',
        popularity: 7,
        date: 1614650400,
        entity: 'programming',
    },
    {
        id: 80,
        title: ['Rust', 'Rust'],
        description: ['Курс, посвященный изучению языка программирования Rust - безопасного и эффективного языка, разработанного Mozilla. Вы изучите основные концепции и принципы работы языка Rust, научитесь писать безопасный и многопоточный код, управлять памятью, работать с системными вызовами и создавать надежные и производительные приложения.', 'A course dedicated to learning the Rust programming language, a safe and efficient language developed by Mozilla. You will learn the basic concepts and principles of the Rust language, learn how to write safe and multi-threaded code, manage memory, work with system calls, and create reliable and performant applications.'],
        logo: 'rust',
        discount: 0,
        queryField: 'раст игра Rust',
        popularity: 8,
        date: 1614564000,
        entity: 'programming',
    },
    {
        id: 81,
        title: ['Objective-C', 'Objective-C'],
        description: ['Курс, посвященный изучению языка программирования Objective-C - языка, используемого для разработки приложений под платформы Apple, включая iOS и macOS. Вы изучите основные концепции и синтаксис языка Objective-C, научитесь создавать приложения с использованием фреймворков Cocoa и Cocoa Touch, работать с объектами, классами, протоколами и другими аспектами разработки под платформы Apple.', 'A course dedicated to learning the Objective-C programming language - the language used to develop applications for Apple platforms, including iOS and macOS. You will learn the basic concepts and syntax of the Objective-C language, learn how to create applications using the Cocoa and Cocoa Touch frameworks, work with objects, classes, protocols, and other aspects of development for the Apple platform.'],
        logo: 'objective-c',
        discount: 0,
        queryField: 'объектив обжектив с Objective-C',
        popularity: 7,
        date: 1614477600,
        entity: 'programming',
    },
    {
        id: 82,
        title: ['Delphi', 'Delphi'],
        description: ['Курс, посвященный изучению языка программирования Delphi - языка, используемого для разработки приложений под платформу Windows. Вы изучите основные концепции и синтаксис языка Delphi, научитесь создавать графические пользовательские интерфейсы, работать с базами данных, обрабатывать события и разрабатывать приложения для Windows.', 'A course dedicated to learning the Delphi programming language - the language used to develop applications for the Windows platform. You will learn the basic concepts and syntax of the Delphi language, learn how to create graphical user interfaces, work with databases, handle events, and develop applications for Windows.'],
        logo: 'delphi',
        discount: 0,
        queryField: 'делфи Delphi',
        popularity: 7,
        date: 1614391200,
        entity: 'programming',
    },
    {
        id: 83,
        title: ['Haskell', 'Haskell'],
        description: ['Курс, посвященный изучению языка программирования Haskell - чистого функционального языка, известного своей строгой типизацией и простотой семантики. Вы изучите основные концепции и принципы работы языка Haskell, научитесь писать функциональный код, работать с типами данных, создавать рекурсивные структуры и использовать монады для организации вычислений.', 'A course dedicated to learning the Haskell programming language, a pure functional language known for its strong typing and simplicity of semantics. You will learn the basic concepts and principles of the Haskell language, learn how to write functional code, work with data types, create recursive structures and use monads to organize calculations.'],
        logo: 'haskell',
        discount: 0,
        queryField: 'хаскел Haskell',
        popularity: 7,
        date: 1614304800,
        entity: 'programming',
    },
    {
        id: 84,
        title: ['Julia', 'Julia'],
        description: ['Курс, посвященный изучению языка программирования Julia - языка, разработанного специально для научных и численных вычислений. Вы изучите основные концепции и синтаксис языка Julia, научитесь писать эффективный код для численных расчетов, работать с массивами, функциями и библиотеками для научных вычислений.', 'A course dedicated to learning the Julia programming language, a language designed specifically for scientific and numerical computing. You will learn the basic concepts and syntax of the Julia language, learn how to write efficient code for numerical calculations, work with arrays, functions and libraries for scientific computing.'],
        logo: 'julia',
        discount: 0,
        queryField: 'жулиа джулиа ждулия Julia',
        popularity: 6,
        date: 1614218400,
        entity: 'programming',
    }
];